### PR TITLE
Add more metabolite and reaction annotations

### PR DESCRIPTION
**Pull request by ChristianLieven**
This PR will add more annotation to the two primary model components: Reactions and Metabolites.

For this I did the following:
  - Inferred metabolite and reaction annotation to MetaNetX by matching ID digits to yeast-GEM 8.3.2.
  - I then proceeded to infer metabolite and reaction annotation to KEGG, BiGG and Biocyc from the MetaNetX 3.1 releases `chem_xref.tsv` and `reac_xref.tsv`.

This addition will allow users to translate the model to their favourite namespace `on-the-fly` without having to resort to external databases nor with having to create their own complicated mapping tables.

This is the first step for us to make the Yarrowia model accessible on the DD-DeCaF platform (https://caffeine.dd-decaf.eu/), since we currently rely on BiGG Identifiers to display a model's fluxes on the maps we provide. However, having an easily accessible cross-mapping may be useful for others too, which is why I wanted to share my work this way :)

Cheers,

Christian

edit by @edkerk:
- [x] fix ([RAVEN issue](https://github.com/SysBioChalmers/RAVEN/issues/196))
- [x] merge with `devel`

### CODE REVIEW

**Comment by ChristianLieven** [comment]
I've already worked out that my mapping is 100% perfect, in fact the following list of metabolites was mapped to wrong MNX IDs and consequently wrong BioCyc, KEGG and BiGG ids.

I'll remove the erroneous mapping in a follow-up commit.

```
y000082 {'c'} PMI12346PH
y000092 {'c'} PMI12346PH
y000547 {'c'} HSDH
y002112 {'c'} FKYNH
y002115 {'c'} ALCD2ir
y002116 {'c'} ALDD2y
y002118 {'c'} TRPTA
y002119 {'c'} TYRTA
y200018 {'c'} AATA
y200019 {'c'} DPR
y200020 {'c'} DDPA
y200023 {'c'} IMDHT
y200024 {'c'} IPPS
y200025 {'c'} IPPS
y200029 {'c'} OMCDC
y200030 {'c'} OMCDC
y200032 {'c'} BPNT
y200033 {'c'} APNn
y200036 {'c'} GCPN
y300007 {'c'} PRICIh
y300023 {'c'} IMDHT
y300024 {'c'} IPPS
y300025 {'c'} IPPS
y300026 {'c'} ARAT
y300032 {'c'} BPNT
y300033 {'c'} APNn
y300036 {'c'} GCPN
y300038 {'c'} DB4PS
y300039 {'c'} DHQTi
y300040 {'c'} DHQS
y300042 {'c'} DDPA
y300058 {'c'} 3HAO
y300060 {'c'} IMDHT_3c2hmp
y300061 {'c'} IPMD
y300062 {'c'} 3MOBDC
y300064 {'c'} 3MOPDC
y300065 {'c'} PSCIT
y300066 {'c'} ADCS
y300067 {'c'} ADCL
y300068 {'c'} ABTA
y300069 {'c'} 4HTHRS
y300073 {'c'} PMI12346PH
y300075 {'c'} MTAP
y300076 {'c'} NTD4
y300078 {'c'} NTD2
```

**Comment by ChristianLieven** [comment]
The model with partial mapping can be found here: https://github.com/ChristianLieven/Yarrowia_lipolytica_W29-GEM/tree/bigg_ids

**Comment by edkerk** [comment]
To review this, I've wanted to pass it through a RAVEN I/O cycle, so that the files should look similar. However, I noticed that RAVEN can currently not I/O SBO terms ([issue](https://github.com/SysBioChalmers/RAVEN/issues/196)), so that would mean all SBO terms would be automatically left out.

**Comment by edkerk** [comment]
RAVEN has been able to to I/O of SBO terms since version 2.3.0. Instead of trying to resolve conflicts in this PR, the code has been refactored in RAVEN using yeast-GEM 8.4.2, see PR #29.

**Pull request closed without merging**
